from redlineos.tools.base_tool import BaseTool
from PySide6.QtCore import QEvent


class SelectTool(BaseTool):
    def on_press(self, event: QEvent) -> None: ...
    def on_move(self, event: QEvent) -> None: ...
    def on_release(self, event: QEvent) -> None: ...
